"""A worked example for every template, verified rather than illustrative.

An agent reading `list_templates` learns a template's name and the parameters it
reads. That is enough to guess at a call and not enough to make one: it does not
say that `solid_spec` is `{"kind", "params", "name"}` rather than the string
"cube", or that a roadmap draws nothing at all without a top-level `start_date`.
Both of those were found by writing these examples, which is the argument for
having them.

Every entry here is checked by the suite, so an example cannot rot into a lie:
- a figure example must draw: not merely render, and not merely differ from the
  same template called bare. A template handed something it cannot use still
  returns a document — `project_network`, harvested from a test that meant it
  as a *negative* case, was given a dependency cycle and answered with a figure
  reading "cyclic dependency, cannot compute". That differs from a bare render
  while putting nothing on the page, so an example has to clear
  `count_data_marks`
- an animation example must produce a plan with no blocking violations
- an example may only use parameters the template actually reads
- `REQUESTS` must route to the template it is filed under

`EXAMPLES` maps a template id to arguments ready to paste: `type` + `params` for
a figure (the `draw` tool), `template` + `params` for an animation (`plan` and
`render`). `REQUESTS` is the other door into the animation lane -- routing is by
keyword and Chinese-first, so these are the phrasings that actually reach each
template. Two templates are absent from it on purpose: `calculus/tangent_shift`
and `conic/cone_slice` are reachable only by id, which is why their invocation
reads `concept-id`.
"""

EXAMPLES = {'3d/cube_section': {'params': {'section_points': ['A', 'B1', 'D1'],
                                'solid_spec': {'kind': 'cube',
                                               'name': 'ABCD-A1B1C1D1',
                                               'params': {'side': 2.0}}},
                     'template': '3d/cube_section'},
 '3d/solid_overview': {'params': {'solid_spec': {'kind': 'cube',
                                                 'name': 'ABCD-A1B1C1D1',
                                                 'params': {'side': 2.0}}},
                       'template': '3d/solid_overview'},
 '3d/sphere_section': {'params': {}, 'template': '3d/sphere_section'},
 '3d/three_views': {'params': {'solid_spec': {'kind': 'cube',
                                              'name': 'ABCD-A1B1C1D1',
                                              'params': {'side': 2.0}}},
                    'template': '3d/three_views'},
 'aoa_work': {'params': {'arcs': [{'duration': 3, 'from': 1, 'label': 'A', 'to': 2},
                                  {'duration': 4, 'from': 2, 'label': 'B', 'to': 3},
                                  {'dummy': True,
                                   'duration': 6,
                                   'from': 1,
                                   'label': 'C',
                                   'to': 3}],
                         'nodes': [{'col': 0, 'id': 1, 'row': 0},
                                   {'col': 1, 'id': 2, 'row': 0},
                                   {'col': 2, 'id': 3, 'row': 1}],
                         'title': 'Network'},
              'type': 'aoa_work'},
 'aon_node': {'params': {'annotated': True,
                         'lag': '2',
                         'nodes': [{'duration': 3, 'id': 'n1', 'name': 'Design'},
                                   {'duration': 5, 'id': 'n2', 'name': 'Build'},
                                   {'duration': 2, 'id': 'n3', 'name': 'Test'}],
                         'title': 'Node'},
              'type': 'aon_node'},
 'architecture_diagram': {'params': {'annotations': [{'near': 'svc',
                                                      'text': 'Stateless tier scales '
                                                              'horizontally'}],
                                     'caption': 'A reusable API template',
                                     'components': [{'id': 'client',
                                                     'label': 'Client (Web/Mobile)',
                                                     'type': 'client'},
                                                    {'id': 'lb',
                                                     'label': 'Load Balancer',
                                                     'type': 'service'},
                                                    {'id': 'svc',
                                                     'label': 'App Service',
                                                     'type': 'service'},
                                                    {'id': 'db',
                                                     'label': 'PostgreSQL',
                                                     'type': 'database'},
                                                    {'id': 'cache',
                                                     'label': 'Redis Cache',
                                                     'type': 'cache'}],
                                     'connections': [{'from': 'client',
                                                      'label': 'HTTPS',
                                                      'to': 'lb'},
                                                     {'from': 'lb', 'to': 'svc'},
                                                     {'from': 'svc',
                                                      'label': 'SQL',
                                                      'to': 'db'},
                                                     {'from': 'svc',
                                                      'label': 'get/set',
                                                      'to': 'cache'}],
                                     'title': 'API-first service architecture'},
                          'type': 'architecture_diagram'},
 'array_state': {'params': {'annotations': [{'index': 1,
                                             'position': 'above',
                                             'text': 'pivot'}],
                            'brackets': [{'from': 1,
                                          'label': 'window',
                                          'position': 'below',
                                          'to': 2}],
                            'caption': 'Sliding window',
                            'indices': True,
                            'pointers': [{'index': 0,
                                          'label': 'left',
                                          'position': 'above'},
                                         {'index': 3,
                                          'label': 'right',
                                          'position': 'below'}],
                            'values': [1, 2, 3, 4]},
                 'type': 'array_state'},
 'binary_tree': {'params': {'annotations': [{'text': 'root', 'value': 8}],
                            'highlights': {'6': 'current', '8': 'visited'},
                            'path': [8, 3, 6],
                            'pointers': [{'label': 'current', 'value': 6}],
                            'root': {'left': {'right': {'value': 6}, 'value': 3},
                                     'right': {'value': 10},
                                     'value': 8}},
                 'type': 'binary_tree'},
 'calculus/derivative_tangent': {'params': {'expression': 'x**2'},
                                 'template': 'calculus/derivative_tangent'},
 'calculus/ftc_accumulation': {'params': {'expression': 'x**2'},
                               'template': 'calculus/ftc_accumulation'},
 'calculus/riemann_integral': {'params': {'expression': 'x**2'},
                               'template': 'calculus/riemann_integral'},
 'calculus/tangent_shift': {'params': {}, 'template': 'calculus/tangent_shift'},
 'calculus/taylor_series': {'params': {'function': 'sin'},
                            'template': 'calculus/taylor_series'},
 'call_stack': {'params': {'caption': 'fib(2) returns 1',
                           'frames': [{'args': {'n': 5},
                                       'function': 'fib',
                                       'state': 'waiting'},
                                      {'args': {'n': 4},
                                       'function': 'fib',
                                       'state': 'waiting'},
                                      {'args': {'n': 3},
                                       'function': 'fib',
                                       'state': 'waiting'},
                                      {'args': {'n': 2},
                                       'function': 'fib',
                                       'return': 1,
                                       'state': 'executing'}],
                           'highlights': {'3': 'current'},
                           'show_return_values': True},
                'type': 'call_stack'},
 'circle_chord_rational': {'params': {'point_label': 'P', 'triple': '3,4,5'},
                           'type': 'circle_chord_rational'},
 'comparison': {'params': {'columns': [{'label': '权责发生制',
                                        'points': ['按权责期确认', '反映经营成果']},
                                       {'label': '收付实现制', 'points': ['按收付确认', '核算简单']}],
                           'title': '两种确认基础'},
                'type': 'comparison'},
 'conic': {'params': {}, 'template': 'conic'},
 'conic/cone_slice': {'params': {'half_angle_tan': 0.5},
                      'template': 'conic/cone_slice'},
 'conic/ellipse_foci': {'params': {}, 'template': 'conic/ellipse_foci'},
 'conic/parabola_focus_directrix': {'params': {},
                                    'template': 'conic/parabola_focus_directrix'},
 'construction': {'params': {'claims': [{'claim': 'perpendicular',
                                         'of': ['[ C D ]', '[ A B ]']},
                                        {'claim': 'midpoint', 'of': ['G', 'A', 'B']},
                                        {'claim': 'congruent',
                                         'of': [['A', 'B'], ['A', 'C'], ['B', 'C']]}],
                             'steps': ['A = 0, 0',
                                       'B = 1, 0',
                                       '( A B )',
                                       '( B A ) -> C D',
                                       '[ C D ]',
                                       '[ A B ]',
                                       '< A B C >'],
                             'title': 'Vesica piscis — the perpendicular bisector, '
                                      'proved'},
                  'type': 'construction'},
 'coordinate_plane': {'params': {'curves': [{'function': '2*cos(x)',
                                             'label': 'theta=pi/2',
                                             'style': 'dashed'},
                                            {'function': '-2*cos(x)',
                                             'label': 'theta=3pi/2',
                                             'style': 'solid'}],
                                 'show_grid': True,
                                 'title': 'Phase choices near x=0',
                                 'x_max': 1.5708,
                                 'x_min': 0,
                                 'y_max': 2.2,
                                 'y_min': -2.2},
                      'type': 'coordinate_plane'},
 'cycle_diagram': {'params': {'center': '循环',
                              'steps': [{'label': '填制凭证'},
                                        {'label': '登记账簿'},
                                        {'label': '试算平衡'},
                                        {'label': '编制报表'}],
                              'title': '会计循环'},
                   'type': 'cycle_diagram'},
 'descent_triangles': {'params': {'first': {'area': 'pq(p−q)(p+q)',
                                            'hyp': 'p²+q²',
                                            'legs': ['p²−q²', '2pq'],
                                            'size': 17},
                                  'note': '2a < a⁴+b⁴',
                                  'second': {'area': 'q = b²',
                                             'hyp': '2a',
                                             'legs': ['d−c', 'd+c'],
                                             'size': 4}},
                       'type': 'descent_triangles'},
 'dirichlet_function': {'params': {'num_points': 60, 'zoom_level': 3},
                        'type': 'dirichlet_function'},
 'dp_table': {'params': {'arrows': [{'from': [1, 2], 'to': [2, 2]}],
                         'caption': 'LCS example',
                         'col_labels': ['', 'a', 'b'],
                         'formula': 'dp[i][j] = max(...)',
                         'highlights': {'1,2': 'dependency', '2,2': 'current'},
                         'row_labels': ['', 'a', 'b'],
                         'values': [[0, 0, 0], [0, 1, 1], [0, 1, 2]]},
              'type': 'dp_table'},
 'environment_diagram': {'params': {'caption': 'Environment after add5 = make_adder(5)',
                                    'frames': [{'bindings': [{'name': 'make_adder',
                                                              'value': 'func:f0'},
                                                             {'name': 'add5',
                                                              'value': 'func:f1'}],
                                                'id': 'global',
                                                'label': 'Global',
                                                'parent': None},
                                               {'bindings': [{'name': 'n',
                                                              'value': '5'}],
                                                'id': 'f1',
                                                'label': 'f1: make_adder',
                                                'parent': 'global'}],
                                    'functions': [{'body': 'lambda x: x + n',
                                                   'id': 'f0',
                                                   'params': ['n'],
                                                   'parent_frame': 'global'},
                                                  {'body': 'x + n',
                                                   'id': 'f1',
                                                   'params': ['x'],
                                                   'parent_frame': 'f1'}],
                                    'highlights': {'bindings': {'f1.n': 'target'},
                                                   'frames': {'f1': 'current'},
                                                   'functions': {'f1': 'current'}}},
                         'type': 'environment_diagram'},
 'flow_diagram': {'params': {'steps': [{'desc': '审核原始凭证', 'label': '填制凭证'},
                                       {'label': '登记账簿'},
                                       {'label': '编制报表'}],
                             'title': '会计核算流程'},
                  'type': 'flow_diagram'},
 'function': {'params': {}, 'template': 'function'},
 'function_graph': {'params': {'fill_area': [{'from': 0.5,
                                              'from_label': 'a',
                                              'to': 3.5,
                                              'to_label': 'b'}],
                               'function': 'sqrt(x)',
                               'x_max': 4,
                               'x_min': 0},
                    'type': 'function_graph'},
 'gantt': {'params': {'tasks': [{'critical': True,
                                 'duration': 3,
                                 'name': '基础',
                                 'start': 0},
                                {'duration': 5, 'name': '主体', 'start': 3}]},
           'type': 'gantt'},
 'geometry': {'params': {}, 'template': 'geometry'},
 'graph': {'params': {'directed': True,
                      'edges': [{'from': '0', 'to': '1', 'weight': 'H'},
                                {'from': '1', 'to': '2', 'weight': 'T'},
                                {'from': '2', 'to': '0', 'weight': 'T'}],
                      'height': 340,
                      'layout': 'custom',
                      'node_radius': 32,
                      'nodes': [{'id': '0', 'label': 'start', 'x': 0.12, 'y': 0.5},
                                {'id': '1', 'label': 'H', 'x': 0.4, 'y': 0.5},
                                {'id': '2', 'label': 'HT', 'x': 0.68, 'y': 0.5}],
                      'weighted': True,
                      'width': 760},
           'type': 'graph'},
 'hash_table': {'params': {'buckets': 6,
                           'caption': 'Collision at bucket 2',
                           'collision_strategy': 'chaining',
                           'entries': [{'bucket': 2, 'key': 'apple', 'value': 5},
                                       {'bucket': 2, 'key': 'cherry', 'value': 7},
                                       {'bucket': 4, 'key': 'banana', 'value': 3}],
                           'highlights': {'bucket': 2, 'key': 'cherry'},
                           'show_hash': True},
                'type': 'hash_table'},
 'heatmap': {'params': {'col_labels': ['c1', 'c2', 'c3', 'c4'],
                        'row_labels': ['r1', 'r2', 'r3'],
                        'show_values': True,
                        'title': 'Grid',
                        'values': [[0.1, 0.5, 0.9, 0.3],
                                   [0.7, 0.2, 0.4, 0.8],
                                   [0.6, 0.05, 0.55, 0.95]]},
             'type': 'heatmap'},
 'lattice_grid': {'params': {'height': 5,
                             'highlighted_points': [[2, 3], [4, 1]],
                             'width': 5},
                  'type': 'lattice_grid'},
 'linear_algebra/linear_map': {'params': {'matrix': [[2, 1], [1, 3]],
                                          'show_determinant': True,
                                          'show_eigenvectors': True,
                                          'vectors': [[1, 0], [0, 1]]},
                               'template': 'linear_algebra/linear_map'},
 'linear_algebra/matmul_views': {'params': {'a': [[1, 2], [3, 4]],
                                            'b': [[5, 6], [7, 8]],
                                            'view': 'row'},
                                 'template': 'linear_algebra/matmul_views'},
 'linked_list': {'params': {'cycle_to': 'n1',
                            'highlights': {'n1': 'visited', 'n2': 'current'},
                            'nodes': [{'id': 'n1', 'value': 1},
                                      {'id': 'n2', 'value': 2},
                                      {'id': 'n3', 'value': 3}],
                            'pointers': [{'label': 'slow', 'node': 'n2'}],
                            'show_null': True,
                            'type': 'singly'},
                 'type': 'linked_list'},
 'matrix_state': {'params': {'arrows': [{'from': [0, 0], 'to': [0, 1]}],
                             'caption': 'BFS traversal on grid',
                             'col_labels': ['c0', 'c1', 'c2'],
                             'highlights': {'0,0': 'visited',
                                            '1,1': 'current',
                                            '2,2': 'target'},
                             'path': [[0, 0], [0, 1], [1, 1]],
                             'row_labels': ['r0', 'r1', 'r2'],
                             'values': [[1, 2, 3], [4, 5, 6], [7, 8, 9]]},
                  'type': 'matrix_state'},
 'matrix_transform': {'params': {'caption': 'Shear', 'matrix': [[2, 1], [1, 3]]},
                      'type': 'matrix_transform'},
 'org_chart': {'params': {'root': {'children': [{'name': 'Someone With An Extremely '
                                                         'Long Name Indeed Who Also '
                                                         'Has Several Additional '
                                                         'Middle Names',
                                                 'title': 'Principal Engineer, '
                                                          'Platform Infrastructure and '
                                                          'Developer Experience'}],
                                   'name': 'Dr. Alexandra '
                                           'Whitfield-Montgomery-Fotheringay-Ashby-de-la-Zouch',
                                   'title': 'Chief Executive Officer and Chair of the '
                                            'Supervisory Board'}},
               'type': 'org_chart'},
 'polar_graph': {'params': {'functions': [{'color': '#FF0000', 'expr': '1+cos(theta)'},
                                          {'color': '#00FF00',
                                           'expr': '1-cos(theta)'}]},
                 'type': 'polar_graph'},
 'project_network': {'params': {'activities': [{'duration': 3,
                                                'id': 'A',
                                                'name': 'Survey',
                                                'predecessors': []},
                                               {'duration': 5,
                                                'id': 'B',
                                                'name': 'Design',
                                                'predecessors': ['A']},
                                               {'duration': 2,
                                                'id': 'C',
                                                'name': 'Procure',
                                                'predecessors': ['A']},
                                               {'duration': 4,
                                                'id': 'D',
                                                'name': 'Build',
                                                'predecessors': ['B', 'C']},
                                               {'duration': 1,
                                                'id': 'E',
                                                'name': 'Handover',
                                                'predecessors': ['D']}]},
                     'type': 'project_network'},
 'queue': {'params': {'back_label': 'back',
                      'caption': 'Dequeue from front, enqueue 5 at back',
                      'front_label': 'front',
                      'highlights': {'0': 'dequeue', '2': 'current'},
                      'operation': {'end': 'back', 'type': 'enqueue', 'value': 5},
                      'values': [3, 7, 2, 9]},
           'type': 'queue'},
 'riemann_sum': {'params': {'a': 0,
                            'b': 2,
                            'function': 'x^2',
                            'n': 5,
                            'show_area_value': True},
                 'type': 'riemann_sum'},
 'roadmap': {'params': {'end_date': '2026-05-01',
                        'items': [{'end_date': '2026-02-10',
                                   'id': 'a',
                                   'start_date': '2026-01-05',
                                   'status': 'complete',
                                   'title': 'Kernel',
                                   'track': 'core'},
                                  {'depends_on': ['a'],
                                   'end_date': '2026-03-20',
                                   'id': 'b',
                                   'start_date': '2026-02-11',
                                   'status': 'active',
                                   'title': 'Lane',
                                   'track': 'core'},
                                  {'end_date': '2026-03-01',
                                   'id': 'c',
                                   'start_date': '2026-02-01',
                                   'status': 'at-risk',
                                   'title': 'Guide',
                                   'track': 'docs'},
                                  {'end_date': '2026-04-01',
                                   'id': 'd',
                                   'start_date': '2026-03-02',
                                   'status': 'planned',
                                   'title': 'Publish',
                                   'track': 'ops'},
                                  {'end_date': '2026-04-20',
                                   'id': 'e',
                                   'start_date': '2026-04-02',
                                   'status': 'tentative',
                                   'title': 'Backfill',
                                   'track': 'ops'}],
                        'milestones': [{'date': '2026-03-01', 'title': 'Beta'},
                                       {'date': '2026-04-15', 'title': 'GA'}],
                        'start_date': '2026-01-01',
                        'title': 'Two halves',
                        'tracks': [{'id': 'core', 'label': 'Core'},
                                   {'id': 'docs', 'label': 'Docs'},
                                   {'id': 'ops', 'label': 'Ops'}]},
             'type': 'roadmap'},
 'stack': {'params': {'annotations': [{'index': 0, 'text': 'bottom'}],
                      'caption': 'Push 5 onto stack',
                      'highlights': {'3': 'current'},
                      'operation': {'type': 'push', 'value': 5},
                      'orientation': 'vertical',
                      'top_label': 'top →',
                      'values': [3, 7, 2, 9]},
           'type': 'stack'},
 'step_function': {'params': {'marker_positions': [2, 3, 5, 6, 7],
                              'transition_x': 5,
                              'x_max': 10,
                              'x_min': 1},
                   'type': 'step_function'},
 'structure_chart': {'params': {'children': [{'children': [{'name': 'parse'},
                                                           {'name': 'lex'}],
                                              'name': 'read'},
                                             {'name': 'plan'},
                                             {'children': [{'name': 'svg'}],
                                              'name': 'emit'}],
                                'root': 'main',
                                'title': 'Modules'},
                     'type': 'structure_chart'},
 't_account': {'params': {'accounts': [{'credit': [{'amount': '60000', 'text': '购买设备'}],
                                        'debit': [{'amount': '100000', 'text': '收到投资'}],
                                        'name': '银行存款'}],
                          'title': '借贷记账'},
               'type': 't_account'},
 'timeline': {'params': {'events': [{'date': '远古', 'desc': '简单计数', 'label': '结绳记事'},
                                    {'date': '1494', 'desc': '帕乔利', 'label': '复式记账'},
                                    {'date': '当代', 'desc': '智能财务', 'label': '会计信息化'}],
                         'title': '会计发展简史'},
              'type': 'timeline'},
 'trig': {'params': {}, 'template': 'trig'},
 'trig/graph_transform': {'params': {'trig_spec': {'amplitude': 2,
                                                   'function': 'sin',
                                                   'period': 2}},
                          'template': 'trig/graph_transform'},
 'trig/unit_circle_to_sine': {'params': {}, 'template': 'trig/unit_circle_to_sine'},
 'unit_circle': {'params': {'angle': 210,
                            'radius_scale': 1.2,
                            'show_common_angles': True,
                            'show_tan': True,
                            'show_triangle': True},
                 'type': 'unit_circle'},
 'wbs': {'params': {'root': {'children': [{'children': [{'name': '方案'},
                                                        {'name': '施工图'}],
                                           'name': '设计'},
                                          {'name': '施工'}],
                             'name': '项目'}},
         'type': 'wbs'}}

REQUESTS = {'3d/cube_section': '正方体 ABCD-A1B1C1D1 过 A、B1、D1 三点的截面',
 '3d/solid_overview': '正方体的整体结构',
 '3d/sphere_section': '球的截面',
 '3d/three_views': '正方体的三视图',
 'calculus/derivative_tangent': '切线随点移动',
 'calculus/ftc_accumulation': '微积分基本定理的累积函数',
 'calculus/riemann_integral': '黎曼和逼近定积分',
 'calculus/taylor_series': '泰勒级数展开',
 'conic': '圆锥曲线的定义',
 'conic/ellipse_foci': '椭圆的两个焦点',
 'conic/parabola_focus_directrix': '抛物线的焦点和准线',
 'function': '画出 y = x^2 - 2x 的图像',
 'geometry': '三角形的性质',
 'linear_algebra/linear_map': '线性变换如何作用于基向量',
 'linear_algebra/matmul_views': '矩阵乘法的行视角',
 'trig': '画一个正弦函数的图像',
 'trig/graph_transform': 'y=2sin(x)的图像变换',
 'trig/unit_circle_to_sine': '单位圆生成正弦曲线的图像'}
