"""Real parameter payloads, one per figure template.

Harvested from the populated `render_diagram({...})` calls already in the
suite, plus hand-written entries for the templates that had none. These exist
so determinism is checked against figures that actually draw something: a
template rendered with `{}` takes its empty defaults and never reaches the
loops where ordering could vary, so a sweep over bare renders agrees with
itself no matter how badly ordered the code beneath it is.

Harvesting them from the suite had one trap worth naming, because it caught
this file. Tests contain deliberately *bad* inputs, and a template handed one
still returns a document — `project_network` was given a dependency cycle and
answered with a figure reading "网络图存在循环依赖，无法计算". That differs from
the bare render, so it satisfied "the payload changed the output" while drawing
nothing at all. An example must therefore clear `count_data_marks`, not merely
differ: refusal chrome is a document, and it is not a drawing.
"""

PAYLOADS = {'aoa_work': {'arcs': [{'duration': 3, 'from': 1, 'label': 'A', 'to': 2},
                       {'duration': 4, 'from': 2, 'label': 'B', 'to': 3},
                       {'dummy': True,
                        'duration': 6,
                        'from': 1,
                        'label': 'C',
                        'to': 3}],
              'nodes': [{'col': 0, 'id': 1, 'row': 0},
                        {'col': 1, 'id': 2, 'row': 0},
                        {'col': 2, 'id': 3, 'row': 1}],
              'title': 'Network'},
 'aon_node': {'annotated': True,
              'lag': '2',
              'nodes': [{'duration': 3, 'id': 'n1', 'name': 'Design'},
                        {'duration': 5, 'id': 'n2', 'name': 'Build'},
                        {'duration': 2, 'id': 'n3', 'name': 'Test'}],
              'title': 'Node'},
 'architecture_diagram': {'annotations': [{'near': 'svc',
                                           'text': 'Stateless tier scales '
                                                   'horizontally'}],
                          'caption': 'A reusable API template',
                          'components': [{'id': 'client',
                                          'label': 'Client (Web/Mobile)',
                                          'type': 'client'},
                                         {'id': 'lb',
                                          'label': 'Load Balancer',
                                          'type': 'service'},
                                         {'id': 'svc',
                                          'label': 'App Service',
                                          'type': 'service'},
                                         {'id': 'db',
                                          'label': 'PostgreSQL',
                                          'type': 'database'},
                                         {'id': 'cache',
                                          'label': 'Redis Cache',
                                          'type': 'cache'}],
                          'connections': [{'from': 'client',
                                           'label': 'HTTPS',
                                           'to': 'lb'},
                                          {'from': 'lb', 'to': 'svc'},
                                          {'from': 'svc', 'label': 'SQL', 'to': 'db'},
                                          {'from': 'svc',
                                           'label': 'get/set',
                                           'to': 'cache'}],
                          'title': 'API-first service architecture'},
 'array_state': {'annotations': [{'index': 1, 'position': 'above', 'text': 'pivot'}],
                 'brackets': [{'from': 1,
                               'label': 'window',
                               'position': 'below',
                               'to': 2}],
                 'caption': 'Sliding window',
                 'indices': True,
                 'pointers': [{'index': 0, 'label': 'left', 'position': 'above'},
                              {'index': 3, 'label': 'right', 'position': 'below'}],
                 'values': [1, 2, 3, 4]},
 'binary_tree': {'annotations': [{'text': 'root', 'value': 8}],
                 'highlights': {'6': 'current', '8': 'visited'},
                 'path': [8, 3, 6],
                 'pointers': [{'label': 'current', 'value': 6}],
                 'root': {'left': {'right': {'value': 6}, 'value': 3},
                          'right': {'value': 10},
                          'value': 8}},
 'call_stack': {'caption': 'fib(2) returns 1',
                'frames': [{'args': {'n': 5}, 'function': 'fib', 'state': 'waiting'},
                           {'args': {'n': 4}, 'function': 'fib', 'state': 'waiting'},
                           {'args': {'n': 3}, 'function': 'fib', 'state': 'waiting'},
                           {'args': {'n': 2},
                            'function': 'fib',
                            'return': 1,
                            'state': 'executing'}],
                'highlights': {'3': 'current'},
                'show_return_values': True},
 'circle_chord_rational': {'point_label': 'P', 'triple': '3,4,5'},
 'comparison': {'columns': [{'label': '权责发生制', 'points': ['按权责期确认', '反映经营成果']},
                            {'label': '收付实现制', 'points': ['按收付确认', '核算简单']}],
                'title': '两种确认基础'},
 'construction': {'claims': [{'claim': 'perpendicular', 'of': ['[ C D ]', '[ A B ]']},
                             {'claim': 'midpoint', 'of': ['G', 'A', 'B']},
                             {'claim': 'congruent',
                              'of': [['A', 'B'], ['A', 'C'], ['B', 'C']]}],
                  'steps': ['A = 0, 0',
                            'B = 1, 0',
                            '( A B )',
                            '( B A ) -> C D',
                            '[ C D ]',
                            '[ A B ]',
                            '< A B C >'],
                  'title': 'Vesica piscis — the perpendicular bisector, proved'},
 'coordinate_plane': {'curves': [{'function': '2*cos(x)',
                                  'label': 'theta=pi/2',
                                  'style': 'dashed'},
                                 {'function': '-2*cos(x)',
                                  'label': 'theta=3pi/2',
                                  'style': 'solid'}],
                      'show_grid': True,
                      'title': 'Phase choices near x=0',
                      'x_max': 1.5708,
                      'x_min': 0,
                      'y_max': 2.2,
                      'y_min': -2.2},
 'cycle_diagram': {'center': '循环',
                   'steps': [{'label': '填制凭证'},
                             {'label': '登记账簿'},
                             {'label': '试算平衡'},
                             {'label': '编制报表'}],
                   'title': '会计循环'},
 'descent_triangles': {'first': {'area': 'pq(p−q)(p+q)',
                                 'hyp': 'p²+q²',
                                 'legs': ['p²−q²', '2pq'],
                                 'size': 17},
                       'note': '2a < a⁴+b⁴',
                       'second': {'area': 'q = b²',
                                  'hyp': '2a',
                                  'legs': ['d−c', 'd+c'],
                                  'size': 4}},
 'dirichlet_function': {'num_points': 60, 'zoom_level': 3},
 'dp_table': {'arrows': [{'from': [1, 2], 'to': [2, 2]}],
              'caption': 'LCS example',
              'col_labels': ['', 'a', 'b'],
              'formula': 'dp[i][j] = max(...)',
              'highlights': {'1,2': 'dependency', '2,2': 'current'},
              'row_labels': ['', 'a', 'b'],
              'values': [[0, 0, 0], [0, 1, 1], [0, 1, 2]]},
 'environment_diagram': {'caption': 'Environment after add5 = make_adder(5)',
                         'frames': [{'bindings': [{'name': 'make_adder',
                                                   'value': 'func:f0'},
                                                  {'name': 'add5', 'value': 'func:f1'}],
                                     'id': 'global',
                                     'label': 'Global',
                                     'parent': None},
                                    {'bindings': [{'name': 'n', 'value': '5'}],
                                     'id': 'f1',
                                     'label': 'f1: make_adder',
                                     'parent': 'global'}],
                         'functions': [{'body': 'lambda x: x + n',
                                        'id': 'f0',
                                        'params': ['n'],
                                        'parent_frame': 'global'},
                                       {'body': 'x + n',
                                        'id': 'f1',
                                        'params': ['x'],
                                        'parent_frame': 'f1'}],
                         'highlights': {'bindings': {'f1.n': 'target'},
                                        'frames': {'f1': 'current'},
                                        'functions': {'f1': 'current'}}},
 'flow_diagram': {'steps': [{'desc': '审核原始凭证', 'label': '填制凭证'},
                            {'label': '登记账簿'},
                            {'label': '编制报表'}],
                  'title': '会计核算流程'},
 'function_graph': {'fill_area': [{'from': 0.5,
                                   'from_label': 'a',
                                   'to': 3.5,
                                   'to_label': 'b'}],
                    'function': 'sqrt(x)',
                    'x_max': 4,
                    'x_min': 0},
 'gantt': {'tasks': [{'critical': True, 'duration': 3, 'name': '基础', 'start': 0},
                     {'duration': 5, 'name': '主体', 'start': 3}]},
 'graph': {'directed': True,
           'edges': [{'from': '0', 'to': '1', 'weight': 'H'},
                     {'from': '1', 'to': '2', 'weight': 'T'},
                     {'from': '2', 'to': '0', 'weight': 'T'}],
           'height': 340,
           'layout': 'custom',
           'node_radius': 32,
           'nodes': [{'id': '0', 'label': 'start', 'x': 0.12, 'y': 0.5},
                     {'id': '1', 'label': 'H', 'x': 0.4, 'y': 0.5},
                     {'id': '2', 'label': 'HT', 'x': 0.68, 'y': 0.5}],
           'weighted': True,
           'width': 760},
 'hash_table': {'buckets': 6,
                'caption': 'Collision at bucket 2',
                'collision_strategy': 'chaining',
                'entries': [{'bucket': 2, 'key': 'apple', 'value': 5},
                            {'bucket': 2, 'key': 'cherry', 'value': 7},
                            {'bucket': 4, 'key': 'banana', 'value': 3}],
                'highlights': {'bucket': 2, 'key': 'cherry'},
                'show_hash': True},
 'heatmap': {'col_labels': ['c1', 'c2', 'c3', 'c4'],
             'row_labels': ['r1', 'r2', 'r3'],
             'show_values': True,
             'title': 'Grid',
             'values': [[0.1, 0.5, 0.9, 0.3],
                        [0.7, 0.2, 0.4, 0.8],
                        [0.6, 0.05, 0.55, 0.95]]},
 'lattice_grid': {'height': 5, 'highlighted_points': [[2, 3], [4, 1]], 'width': 5},
 'linked_list': {'cycle_to': 'n1',
                 'highlights': {'n1': 'visited', 'n2': 'current'},
                 'nodes': [{'id': 'n1', 'value': 1},
                           {'id': 'n2', 'value': 2},
                           {'id': 'n3', 'value': 3}],
                 'pointers': [{'label': 'slow', 'node': 'n2'}],
                 'show_null': True,
                 'type': 'singly'},
 'matrix_state': {'arrows': [{'from': [0, 0], 'to': [0, 1]}],
                  'caption': 'BFS traversal on grid',
                  'col_labels': ['c0', 'c1', 'c2'],
                  'highlights': {'0,0': 'visited', '1,1': 'current', '2,2': 'target'},
                  'path': [[0, 0], [0, 1], [1, 1]],
                  'row_labels': ['r0', 'r1', 'r2'],
                  'values': [[1, 2, 3], [4, 5, 6], [7, 8, 9]]},
 'matrix_transform': {'matrix': [[2, 1], [1, 3]], 'title': 'Shear'},
 'org_chart': {'root': {'children': [{'name': 'Someone With An Extremely Long Name '
                                              'Indeed Who Also Has Several Additional '
                                              'Middle Names',
                                      'title': 'Principal Engineer, Platform '
                                               'Infrastructure and Developer '
                                               'Experience'}],
                        'name': 'Dr. Alexandra '
                                'Whitfield-Montgomery-Fotheringay-Ashby-de-la-Zouch',
                        'title': 'Chief Executive Officer and Chair of the Supervisory '
                                 'Board'}},
 'polar_graph': {'functions': [{'color': '#FF0000', 'expr': '1+cos(theta)'},
                               {'color': '#00FF00', 'expr': '1-cos(theta)'}]},
 'project_network': {'activities': [{'duration': 3,
                                     'id': 'A',
                                     'name': 'Survey',
                                     'predecessors': []},
                                    {'duration': 5,
                                     'id': 'B',
                                     'name': 'Design',
                                     'predecessors': ['A']},
                                    {'duration': 2,
                                     'id': 'C',
                                     'name': 'Procure',
                                     'predecessors': ['A']},
                                    {'duration': 4,
                                     'id': 'D',
                                     'name': 'Build',
                                     'predecessors': ['B', 'C']},
                                    {'duration': 1,
                                     'id': 'E',
                                     'name': 'Handover',
                                     'predecessors': ['D']}]},
 'queue': {'back_label': 'back',
           'caption': 'Dequeue from front, enqueue 5 at back',
           'front_label': 'front',
           'highlights': {'0': 'dequeue', '2': 'current'},
           'operation': {'end': 'back', 'type': 'enqueue', 'value': 5},
           'type': 'deque',
           'values': [3, 7, 2, 9]},
 'riemann_sum': {'a': 0, 'b': 2, 'function': 'x^2', 'n': 5, 'show_area_value': True},
 'roadmap': {'end_date': '2026-05-01',
             'items': [{'end_date': '2026-02-10',
                        'id': 'a',
                        'start_date': '2026-01-05',
                        'status': 'complete',
                        'title': 'Kernel',
                        'track': 'core'},
                       {'depends_on': ['a'],
                        'end_date': '2026-03-20',
                        'id': 'b',
                        'start_date': '2026-02-11',
                        'status': 'active',
                        'title': 'Lane',
                        'track': 'core'},
                       {'end_date': '2026-03-01',
                        'id': 'c',
                        'start_date': '2026-02-01',
                        'status': 'at-risk',
                        'title': 'Guide',
                        'track': 'docs'},
                       {'end_date': '2026-04-01',
                        'id': 'd',
                        'start_date': '2026-03-02',
                        'status': 'planned',
                        'title': 'Publish',
                        'track': 'ops'},
                       {'end_date': '2026-04-20',
                        'id': 'e',
                        'start_date': '2026-04-02',
                        'status': 'tentative',
                        'title': 'Backfill',
                        'track': 'ops'}],
             'milestones': [{'date': '2026-03-01', 'title': 'Beta'},
                            {'date': '2026-04-15', 'title': 'GA'}],
             'start_date': '2026-01-01',
             'title': 'Two halves',
             'tracks': [{'id': 'core', 'label': 'Core'},
                        {'id': 'docs', 'label': 'Docs'},
                        {'id': 'ops', 'label': 'Ops'}]},
 'stack': {'annotations': [{'index': 0, 'text': 'bottom'}],
           'caption': 'Push 5 onto stack',
           'highlights': {'3': 'current'},
           'operation': {'type': 'push', 'value': 5},
           'orientation': 'vertical',
           'top_label': 'top →',
           'values': [3, 7, 2, 9]},
 'step_function': {'marker_positions': [2, 3, 5, 6, 7],
                   'transition_x': 5,
                   'x_max': 10,
                   'x_min': 1},
 'structure_chart': {'children': [{'children': [{'name': 'parse'}, {'name': 'lex'}],
                                   'name': 'read'},
                                  {'name': 'plan'},
                                  {'children': [{'name': 'svg'}], 'name': 'emit'}],
                     'root': 'main',
                     'title': 'Modules'},
 't_account': {'accounts': [{'credit': [{'amount': '60000', 'text': '购买设备'}],
                             'debit': [{'amount': '100000', 'text': '收到投资'}],
                             'name': '银行存款'}],
               'title': '借贷记账'},
 'timeline': {'events': [{'date': '远古', 'desc': '简单计数', 'label': '结绳记事'},
                         {'date': '1494', 'desc': '帕乔利', 'label': '复式记账'},
                         {'date': '当代', 'desc': '智能财务', 'label': '会计信息化'}],
              'title': '会计发展简史'},
 'unit_circle': {'angle': 210,
                 'radius_scale': 1.2,
                 'show_common_angles': True,
                 'show_tan': True,
                 'show_triangle': True},
 'wbs': {'root': {'children': [{'children': [{'name': '方案'}, {'name': '施工图'}],
                                'name': '设计'},
                               {'name': '施工'}],
                  'name': '项目'}}}
